[package]
name = "rust-microservice"
version = "0.1.0"
authors = ["Gene Kuo <yuchiung10@yahoo.com.tw>"]
edition = "2018"

[dependencies]
hyper = "0.12"
futures = "0.1"
slab = "0.4.2"
lazy_static = "1.4.0"
regex = "1.4.2"
